[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.48"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# A basic redirects rule
[[redirects]]
  from = "http://reverent-euclid-38d2be.netlify.com/*"
  to = "http://www.solielim.com/:splat 301!"
